core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),  # Админ-панель
    path('', homepage, name='homepage'),
    path('recipes/', include('recipe.urls')),  # Подключение маршрутов из recipe
    path('blog/', include('blog.urls')),  # Подключение маршрутов из blog
    path('eventmanager/', include('eventmanager.urls')),  # Подключение маршрутов из blog
]


# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipe/urls.py
from django.urls import path
from . import views


app_name = 'recipe'

urlpatterns = [
    path('list/', views.recipes, name='recipe_list'),
    path('update_recipe/<int:id>/', views.update_recipe, name='update_recipe'),
    path('delete_recipe/<int:id>/', views.delete_recipe, name='delete_recipe'),
    path('api_recipe/v1/', views.api_recipe, name='api_recipe'),
]

recipe/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User



class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    recipe_name = models.CharField(max_length=100)
    recipe_description = models.TextField()
    recipe_image = models.ImageField(upload_to="recipe")
    recipe_view_count = models.PositiveIntegerField(default=1)

recipe/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import redirect
from .models import Recipe
from django.http import HttpResponse, JsonResponse

def recipes(request):
    if request.method == 'POST':
        data = request.POST
        recipe_image = request.FILES.get('recipe_image')
        recipe_name = data.get('recipe_name')
        recipe_description = data.get('recipe_description')

        Recipe.objects.create(
            recipe_image=recipe_image,
            recipe_name=recipe_name,
            recipe_description=recipe_description,
        )
        return redirect('recipe:recipe_list')

    queryset = Recipe.objects.all()

    if request.GET.get('search'):
        queryset = queryset.filter(
            recipe_name__icontains=request.GET.get('search'))

    context = {'recipes': queryset}
    return render(request, 'recipe/recipes.html', context)

def delete_recipe(request, id):
    queryset = Recipe.objects.get(id=id)
    queryset.delete()
    return redirect('recipe:recipe_list')

def update_recipe(request, id):
    queryset = Recipe.objects.get(id=id)

    if request.method == 'POST':
        data = request.POST
        recipe_image = request.FILES.get('recipe_image')
        recipe_name = data.get('recipe_name')
        recipe_description = data.get('recipe_description')

        queryset.recipe_name = recipe_name
        queryset.recipe_description = recipe_description

        if recipe_image:
            queryset.recipe_image = recipe_image

        queryset.save()
        return redirect('recipe:recipe_list')
    
    context = {'recipe': queryset}
    return render(request, 'recipe/update_recipe.html', context)

def api_recipe(request):
    recipes = Recipe.objects.all()
    recipes_data = list(recipes.values())
    return JsonResponse({'recipe': recipes_data}, safe=False)

recipe/templates/recipe/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Recipes</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    </head>

    <body>
    {% block content %}{% endblock content %}
    </body>
</html>

recipe/templates/recipe/recipes.html
{% extends "recipe/base.html" %}
{% block content %}
<div class="container mt-5">

    <!-- Search Form -->
    <form method="get" action="" class="mb-4">
        <div class="input-group col-6 mx-auto">
            <input type="text" name="search" class="form-control" placeholder="Search for recipes..." value="{{ request.GET.search }}">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </div>
    </form>

    <!-- Add Recipe Form -->
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="text  text-center"> My Recipes </h2>
        <br>
        <h3>Add Recipe</h3>
        <hr>
        <div class="form-group">
            <label>Recipe name</label>
            <input name="recipe_name" type="text" class="form-control" required>
        </div>
        <div class="form-group">
            <label>Recipe description</label>
            <textarea name="recipe_description" class="form-control" required></textarea>
        </div>
        <div class="form-group">
            <label>Recipe Image</label>
            <input name="recipe_image" type="file" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Add Recipe</button>
    </form>

    <!-- Display Recipes -->
    <div class="mt-5">
        <h3>Recipes</h3>
        <hr>
        {% if recipes %}
            <div class="row">
                {% for recipe in recipes %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img src="{{ recipe.recipe_image.url }}" alt="Recipe Image" class="img-fluid" style="max-width: 200px;"><br>
                            <div class="card-body">
                                <h5 class="card-title">{{ recipe.recipe_name }}</h5>
                                <a href ="{% url 'recipe:update_recipe' recipe.id%}" class = "btn btn-success">Edite Recipe</a>  
                                <a href ="{% url 'recipe:delete_recipe' recipe.id%}" class = "btn btn-danger">Delete Recipe</a> 
                                <p class="card-text">{{ recipe.recipe_description }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No recipes found.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

recipe/templates/recipe/update_recipe.html
{% extends "recipe/base.html" %}
{% block content %}
 

<div class="container mt-5">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="text  text-center"> My Recipes </h2>
        <h3>Update Recipe</h3>
        <hr>
        <div class="form-group">
            <label>Recipe name</label>
            <input name="recipe_name" value="{{recipe.recipe_name}}" type="text" class="form-control" required>
        </div>
        <div class="form-group">
            <label>Recipe description</label>
            <textarea name="recipe_description" class="form-control" required>{{recipe.recipe_description}}</textarea>
        </div>
        <div class="form-group">
            <label>Recipe Image</label>
            <input name="recipe_image" type="file" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Update Recipe</button>
    </form>
</div>

{% endblock %}